#!/bin/sh -eu

if [ ! -d .git/hooks ]; then
  echo "Error: Please run this script from the root of the repository."
  exit 1;
fi

# Resolve PHP cmd.
dockerCmd=""
phpService=""
phpCmd=""

read -p "Enter absolute path to module directory (wp-content/plugins/resursbank-woocommerce) within PHP container (no trailing slash): " dir
read -p "Running PHP in Docker (y/n)?" localPhp
case "$localPhp" in
  y|Y ) read -p "Enter name of docker compose command (eg. docker compose or docker-compose): " dockerCmd; read -p "Enter name of php server (eg. php or phpfpm): " phpService; phpCmd="${dockerCmd} exec -w ${dir} -T ${phpService}";;
  n|N ) read -p "Enter name of/path to php binary (eg. php): " php;;
  * ) echo "Invalid response."; exit 1;;
esac

if [ ! -d ./qa/bin ]; then
  mkdir -p ./qa/bin
fi

# Install Composer if it's not already available.
if [ ! -f ./qa/bin/composer ]; then
  echo ""
  echo ""
  echo "--==( Installing Composer )==--"
  echo ""
  curl -L https://github.com/composer/composer/releases/latest/download/composer.phar -o ./qa/bin/composer
  echo ""
  echo ""
fi

chmod +x ./qa/bin/composer

echo ""
echo ""
echo "--==( Setting up git pre-commit hook )==--"
echo ""
echo ""

# Create git pre-commit hook file.
HOOK_FILE=".git/hooks/pre-commit"

if [ -f $HOOK_FILE ]; then
  rm -f $HOOK_FILE
fi

touch $HOOK_FILE
chmod +x $HOOK_FILE

cat <<EOT >> $HOOK_FILE
#!/usr/bin/env -S bash

ERRORS=0

echo "====================================================== ====="
echo ""

echo "==========================================================="
echo "#                                                         #"
echo "#             APPLYING AUTOMATIC ADJUSTMENTS              #"
echo "#                                                         #"
echo "==========================================================="
echo ""

SRC_FILES=""

for file in \$(git diff --name-only --cached)
do
  if [ "\$(echo \$file | cut -d/ -f1)" = "src" ] && [ -f "$dir/\$file" ]; then
      SRC_FILES="\$SRC_FILES $dir/\$file"
  fi
done

if [ -n "\$SRC_FILES" ]; then
  echo ""
  echo ""
  echo "---==( Automatically adjusting src files )==---"
  echo ""
  echo ""
  echo "[APPLYING PSR-12 RULESET]"
  echo ""
  $phpCmd $dir/vendor/bin/phpcbf --extensions=php --standard=PSR12 \$SRC_FILES
  echo ""
  echo ""
  echo "[APPLYING CUSTOM RULESET]"
  echo ""
  $phpCmd $dir/vendor/bin/phpcbf --extensions=php --standard=qa/phpcs/src.xml \$SRC_FILES
else
  echo ""
  echo ""
  echo "No fixable errors found."
  echo ""
  echo ""
fi

echo ""
echo ""
echo "==========================================================="
echo "#                                                         #"
echo "#                  SCANNING SOURCE FILES                  #"
echo "#                                                         #"
echo "==========================================================="
echo ""
echo ""

echo "---==( Executing PHPCS for source files. )==---"
echo ""
if ! $phpCmd $dir/vendor/bin/phpcs --extensions=php,phtml --standard=PSR12 --ignore=Service/,Module/ $dir/src; then
  ERRORS=1
fi
echo ""
if ! $phpCmd $dir/vendor/bin/phpcs --extensions=php,phtml --standard=qa/phpcs/src.xml --ignore=Service/,Module/,Exception/ $dir/src; then
  ERRORS=1
fi
echo ""

echo "---==( Executing PHPMD tests on source files. )==---"
echo ""
if ! $phpCmd $dir/vendor/bin/phpmd $dir/src text $dir/qa/phpmd/src.xml; then
  ERRORS=1
fi
echo ""

if [ "\${ERRORS}" = "1" ]; then
  exec < /dev/tty
  read -p "Continue commit despite remaining errors? (y/n)?" continueCommit
  case "\$continueCommit" in
    y|Y ) exit 0;;
    * ) echo "Aborting."; exit 1;;
  esac
fi
EOT

echo ""
echo ""
echo "--==( Setting up QA tools )==--"
echo ""
echo ""

# Create composer.json file for QA tools.
if [ -f ./composer.json ]; then
  rm -f ./composer.json
fi

if [ -f ./composer.lock ]; then
  rm -f ./composer.lock
fi

touch ./composer.json

cat <<EOT >> ./composer.json
{
  "require-dev": {
    "phpunit/phpunit": "^9",
    "phpmd/phpmd": "^2",
    "squizlabs/php_codesniffer": "^3",
    "slevomat/coding-standard": "~8.0"
  },
  "require": {
    "php": "8.1.*",
    "ext-curl": "*"
  },
   "config": {
     "allow-plugins": {
       "dealerdirect/phpcodesniffer-composer-installer": true
     }
   }
}
EOT

# Install composer packages for QA tools.
$phpCmd $dir/qa/bin/composer install

echo OK
exit 0
